FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV UVICORN_CMD="uvicorn main:app --host 0.0.0.0 --port 8000"
CMD ["sh", "-c", "$UVICORN_CMD"]
