apiVersion: batch/v1
kind: CronJob
metadata:
  name: extractor
spec:
  schedule: "*/15 * * * *"  # каждые 15 минут
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: extractor
            image: extractor:latest
            imagePullPolicy: Never
          restartPolicy: OnFailure
